[package]
name = "main"
version = "0.1.0"
authors = ["Gnaphron <gnaphron@gmail.com>"]
edition = "2018"

[dependencies]
handler = { path = "../function" }
hyper = "0.14"
tokio = { version = "1.0", features = ["macros"] }
